export {default as Navbar} from "./Navbar"
export {default as CTA} from "./CTA"
export {default as Billing} from "./Billing"
export {default as CardDeal} from "./CardDeal"
export {default as Bussiness} from "./Bussiness"
export {default as Client} from "./Client"
export {default as Stats    } from "./Stats"
export {default as Footer} from "./Footer"
export {default as Testimonials} from "./Testimonials"
export {default as Hero} from "./Hero"
